{
 "title": "Assignments Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Assignments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "assignment_request_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reassignments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reassignment_request_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Check AEC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "check_request_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Accepted AEC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "assignments_completed_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assignment_logs_request_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SII Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "columns": [ "Computed.AverageResponseTime" ],
     "group": {
      "GroupARN": "arn:aws:xray:us-east-1:077317418708:group/Default",
      "GroupName": "Default",
      "InsightsConfiguration": {
       "InsightsEnabled": false,
       "NotificationsEnabled": false
      }
     },
     "region": "default"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 11, "w": 15, "x": 0, "y": 4 } },
  {
   "title": "Assignments Traces",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "group": {
      "GroupARN": "arn:aws:xray:us-east-1:077317418708:group/Default",
      "GroupName": "Default",
      "InsightsConfiguration": {
       "InsightsEnabled": false,
       "NotificationsEnabled": false
      }
     },
     "query": "service(id(name: \"Assignment request\"))",
     "region": "default"
    }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "assignments_error_counter", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Schema",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assignments_error_schema_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assignments_error_signature_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Document",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assignments_error_document_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Assignment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assignments_error_assignment_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assignments_error_invalid_token_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Company",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assignments_error_invalid_company_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authorized user",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assignments_error_not_authorized_counter",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tets error alerting ",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(assignments_error_counter)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}